mod 'puppet-nginx', '0.15.0'
mod 'puppetlabs-stdlib', '5.1.0'
mod 'puppetlabs-concat', '5.2.0'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'puppetlabs-docker', '3.1.0'
mod 'puppetlabs-apt', '6.2.1'
mod 'puppetlabs-translate', '1.2.0'
mod 'puppetlabs-powershell', '2.2.0'
mod 'puppetlabs-reboot', '2.1.2'
