mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs-apt', '6.2.1'
mod 'puppetlabs-translate', '1.2.0'
mod 'puppetlabs-powershell', '2.2.0'
mod 'puppetlabs-reboot', '2.1.2'
